
export const busketTypes = {
BUSKED_INC:"BUSKED_INC",
BUSKED_DEC:"BUSKED_DEC",
BUSKED_INFO:'BUSKED_INFO',
BUSKED_BROW:'BUSKED_BROW',
OPENMODAL:'OPENMODAL',
CLOSEMODAL:'CLOSEMODAL',
ADDCARD:'ADDCARD'
}